alias gs="git status"
alias gf="git fetch"
alias gd="git diff"
alias gco="git checkout"
alias gds="git diff --stat-width=200"
alias gca="git commit --amend"
alias gm="gco master"
alias gb="git symbolic-ref --short HEAD 2>/dev/null"
alias gp="git pull"
alias gpm="gco master; git pull; gco -;"
alias gpo="git pull origin \$(gb)"
alias grho="git reset --hard origin/\$(gb)"
alias gcp="git cherry-pick"
alias gr="git rebase"
alias grm="git rebase master"
alias gra="git rebase --abort"
alias grc="git rebase --continue"
alias gcrc="gco release-candidate"
